// AUTH ACTIONS
export const SIGN_UP_REQUESTED = 'SIGN_UP_REQUESTED';
export const SIGN_UP_SUCCEEDED = 'SIGN_UP_SUCCEEDED';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const LOG_IN_REQUESTED = 'LOG_IN_REQUESTED';
export const LOG_IN_SUCCEEDED = 'LOG_IN_SUCCEEDED';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';
export const CHECK_AUTH_REQUESTED = 'CHECK_AUTH_REQUESTED';
export const CHECK_AUTH_SUCCEEDED = 'CHECK_AUTH_SUCCEEDED';
export const CHECK_AUTH_FAILED = 'CHECK_AUTH_FAILED';

// MIDI ACTIONS
export const IS_PLAYING_TRUE = 'IS_PLAYING_TRUE';
export const IS_PLAYING_FALSE = 'IS_PLAYING_FALSE';
export const NOTE_ACTIVATED = 'NOTE_ACTIVATED';
export const NOTE_DEACTIVATED = 'NOTE_DEACTIVATED';
export const NOTE_ADDED_TO_HISTORY = 'NOTE_ADDED_TO_HISTORY';
// export const CHANGE_SOUND_TYPE = 'CHANGE_SOUND_TYPE';

// UI ACTIONS
export const SWITCH_AUTH_FORM = 'SWITCH_AUTH_FORM';
