// AUTH
export const SIGN_UP_REQUESTED = 'SIGN_UP_REQUESTED';
export const SIGN_UP_SUCCEEDED = 'SIGN_UP_SUCCEEDED';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const LOG_IN_REQUESTED = 'LOG_IN_REQUESTED';
export const LOG_IN_SUCCEEDED = 'LOG_IN_SUCCEEDED';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';
export const LOG_OUT_REQUESTED = 'LOG_OUT_REQUESTED';
export const LOG_OUT_SUCCEEDED = 'LOG_OUT_SUCCEEDED';
export const CHECK_AUTH_REQUESTED = 'CHECK_AUTH_REQUESTED';
export const CHECK_AUTH_SUCCEEDED = 'CHECK_AUTH_SUCCEEDED';
export const CHECK_AUTH_FAILED = 'CHECK_AUTH_FAILED';

// UI
export const SWITCH_TO_LOG_IN = 'SWITCH_TO_LOG_IN';
export const SWITCH_TO_SIGN_UP = 'SWITCH_TO_SIGN_UP';
